import React from 'react';



const ParentComponent = () => {
  // Structure de données représentant les continents et leurs pays
  const countryData = {
    Africa: {
      Algeria: false,
      Angola: false,
      Benin: false,
      Botswana: false,
      BurkinaFaso: false,
      Burundi: false,
      Cameroon: false,
      CapeVerde: false,
      CentralAfricanRepublic: false,
      Chad: false,
      Comoros: false,
      DemocraticRepublicOfTheCongo: false,
      Djibouti: false,
      Egypt: false,
      EquatorialGuinea: false,
      Eritrea: false,
      Eswatini: false,
      Ethiopia: false,
      Gabon: false,
      Gambia: false,
      Ghana: false,
      Guinea: false,
      GuineaBissau: false,
      IvoryCoast: false,
      Kenya: false,
      Lesotho: false,
      Liberia: false,
      Libya: false,
      Madagascar: false,
      Malawi: false,
      Mali: false,
      Mauritania: false,
      Mauritius: false,
      Morocco: false,
      Mozambique: false,
      Namibia: false,
      Niger: false,
      Nigeria: false,
      RepublicOfTheCongo: false,
      Rwanda: false,
      SaoTomeAndPrincipe: false,
      Senegal: false,
      Seychelles: false,
      SierraLeone: false,
      Somalia: false,
      SouthAfrica: false,
      SouthSudan: false,
      Sudan: false,
      Tanzania: false,
      Togo: false,
      Tunisia: false,
      Uganda: false,
      Zambia: false,
      Zimbabwe: false
    },
    Asia: {
      Afghanistan: false,
      Armenia: false,
      Azerbaijan: false,
      Bahrain: false,
      Bangladesh: false,
      Bhutan: false,
      Brunei: false,
      Cambodia: false,
      China: false,
      Cyprus: false,
      Georgia: false,
      India: false,
      Indonesia: false,
      Iran: false,
      Iraq: false,
      Israel: false,
      Japan: false,
      Jordan: false,
      Kazakhstan: false,
      Kuwait: false,
      Kyrgyzstan: false,
      Laos: false,
      Lebanon: false,
      Malaysia: false,
      Maldives: false,
      Mongolia: false,
      Myanmar: false,
      Nepal: false,
      NorthKorea: false,
      Oman: false,
      Pakistan: false,
      Palestine: false,
      Philippines: false,
      Qatar: false,
      SaudiArabia: false,
      Singapore: false,
      SouthKorea: false,
      SriLanka: false,
      Syria: false,
      Taiwan: false,
      Tajikistan: false,
      Thailand: false,
      TimorLeste: false,
      Turkey: false,
      Turkmenistan: false,
      UnitedArabEmirates: false,
      Uzbekistan: false,
      Vietnam: false,
      Yemen: false
    },
    Europe: {
      Albania: false,
      Andorra: false,
      Austria: false,
      Belarus: false,
      Belgium: false,
      BosniaAndHerzegovina: false,
      Bulgaria: false,
      Croatia: false,
      CzechRepublic: false,
      Denmark: false,
      Estonia: false,
      Finland: false,
      France: false,
      Germany: false,
      Greece: false,
      Hungary: false,
      Iceland: false,
      Ireland: false,
      Italy: false,
      Kosovo: false,
      Latvia: false,
      Liechtenstein: false,
      Lithuania: false,
      Luxembourg: false,
      Malta: false,
      Moldova: false,
      Monaco: false,
      Montenegro: false,
      Netherlands: false,
      NorthMacedonia: false,
      Norway: false,
      Poland: false,
      Portugal: false,
      Romania: false,
      Russia: false,
      SanMarino: false,
      Serbia: false,
      Slovakia: false,
      Slovenia: false,
      Spain: false,
      Sweden: false,
      Switzerland: false,
      Ukraine: false,
      UnitedKingdom: false,
      VaticanCity: false
    },
    NorthAmerica: {
      AntiguaAndBarbuda: false,
      Bahamas: false,
      Barbados: false,
      Belize: false,
      Canada: false,
      CostaRica: false,
      Cuba: false,
      Dominica: false,
      DominicanRepublic: false,
      ElSalvador: false,
      Grenada: false,
      Guatemala: false,
      Haiti: false,
      Honduras: false,
      Jamaica: false,
      Mexico: false,
      Nicaragua: false,
      Panama: false,
      SaintKittsAndNevis: false,
      SaintLucia: false,
      SaintVincentAndTheGrenadines: false,
      TrinidadAndTobago: false,
      UnitedStates: false
    },
    Oceania: {
      Australia: false,
      Fiji: false,
      Kiribati: false,
      MarshallIslands: false,
      Micronesia: false,
      Nauru: false,
      NewZealand: false,
      Palau: false,
      PapuaNewGuinea: false,
      Samoa: false,
      SolomonIslands: false,
      Tonga: false,
      Tuvalu: false,
      Vanuatu: false
    },
    SouthAmerica: {
      Argentina: false,
      Bolivia: false,
      Brazil: false,
      Chile: false,
      Colombia: false,
      Ecuador: false,
      Guyana: false,
      Paraguay: false,
      Peru: false,
      Suriname: false,
      Uruguay: false,
      Venezuela: false
    },
    Antarctica: {
      // L'Antarctique n'a généralement pas de pays habités
    }
    // Ajoutez d'autres continents et pays selon vos besoins
  };

  return (
    <div>
      <h1>Liste des pays</h1>
      <CountryListRenderer data={countryData} />
    </div>
  );
};

export default ParentComponent;
